# holding pattern
name: v2 Super-Linter Checking 

# Triggers workflow on push or pull request
on: #workflow_dispatch #[repository_dispatch]
  push:
    branches: 
     - master
     - main
  pull_request:
    branches: 
     - master
     - main

  workflow_dispatch:
    inputs:
      name:
        description: 'StartGithubSuperLinter'
        required: true
        default: 'GithubSuperLinter'

  ################################
  # Run Linter against code base #
  ################################
jobs:
  start_test:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Start ${{ github.event.inputs.name }}!"

      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with: 
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint with Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: ./*.java
          VALIDATE_JAVA:	true
          VALIDATE_MARKDOWN:	true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
