# holding pattern
name: v2 Super-Linter Checking 

# Triggers workflow on push or pull request
on: #workflow_dispatch #[repository_dispatch]
  push:
    branches: 
     - master
     - main
  pull_request:
    branches: 
     - master
     - main
  workflow_dispatch:


################################
# Run Linter against code base #
################################
  - name: Lint Code Base
    uses: docker://github/super-linter:v4
    env:
      VALIDATE_ALL_CODEBASE: false
