################################
# Run Linter against code base #
################################
- name: Lint Code Base
  uses: docker://github/super-linter:v4
  env:
    VALIDATE_ALL_CODEBASE: false
