# holding pattern
name: v2 Super-Linter Checking 

# Triggers workflow on push or pull request
on: #workflow_dispatch #[repository_dispatch]
  push:
    branches: 
     - master
     - main
  pull_request:
    branches: 
     - master
     - main

  workflow_dispatch:
    inputs:
      name:
        description: 'StartGithubSuperLinter'
        required: true
        default: 'GithubSuperLinter'

  ################################
  # Run Linter against code base #
  ################################
jobs:
  start_test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Start ${{ github.event.inputs.name }}!"

# Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 2

      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          VALIDATE_ALL_CODEBASE: false
